### ISSUE TITLE
refaire un parser suite à l'évolution du fichier source fantoir vers TOPO

### ISSUE THREAD

**Issue by mmortier** [etalab/fantoir-parser#14]
La DGFIP va diffuser l'information du fantoir dans un fichier "TOPO" qui va subir des modifications de format. Recréer un topo-parser. Prévu pour février 2023.

**Comment by mmortier** [comment]
Le format livré ne correspond pas à ce qui était attendu. Reprendre le code du parser.

**Comment by mmortier** [comment]
Décision du 4 mars de ne plus mettre à jour le parser pour TOPO.

**Comment by landryb** [comment]
pour info, la transformation inverse TOPO->FANTOIR est possible avec https://github.com/landryb/topo2fantoir
